defmodule AdventOfCode.CosmicExpansionTest do
  use ExUnit.Case

  import AdventOfCode.CosmicExpansion, only: [answer: 1]

  test ".answer/1 returns sum of shortest path lengths for all galaxy pairs" do
    input = ~S"""
    ...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....
    """

    assert answer(input) == 374
  end
end
